function fig = ekg()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load ekg
	
h0 = figure('Color',[0.8 0.8 0.8], ...
   'CreateFcn','ekgmhl start', ...
   'NumberTitle','off', ...
   'Name','ECG analysis', ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'PointerShapeCData',mat1, ...
	'Position',[40 40 560 420], ...
	'Tag','base');
h1 = uimenu('Parent',h0, ...
	'Callback','ekgmhl destall, ekgmhl subjinit, ekgmhl subjhl', ...
	'Label','Subject manager', ...
	'Tag','SubjM');
h1 = uimenu('Parent',h0, ...
	'Callback','ekgmhl destall, ekgmhl opents, ekgmhl results', ...
	'Label','Open timeseries', ...
	'Tag','OpenM');
h1 = uimenu('Parent',h0, ...
	'Callback','ekgmhl savets', ...
	'Enable','off', ...
	'Label','Save timeseries', ...
	'Tag','SaveM');
h1 = uimenu('Parent',h0, ...
	'Callback','close', ...
	'Label','Exit', ...
	'Tag','ExitM');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[66 242.25 64.5 18], ...
	'String','Family name', ...
	'Style','text', ...
	'Tag','FamNameT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[65.25 211.5 64.5 18], ...
	'String','First name', ...
	'Style','text', ...
	'Tag','SurNameT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[65.25 178.5 64.5 18], ...
	'String','ID', ...
	'Style','text', ...
	'Tag','IDT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[65.25 138 64.5 27.75], ...
	'String','Date of birth (yyyy/mm/dd)', ...
	'Style','text', ...
	'Tag','BirthDayT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[137.25 242.25 68.25 19.5], ...
	'Style','edit', ...
	'Tag','FamName', ...
	'UserData',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[137.25 211.5 68.25 19.5], ...
	'Style','edit', ...
	'Tag','SurName', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[137.25 178.5 68.25 19.5], ...
	'Style','edit', ...
	'Tag','ID', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[137.25 146.25 33.75 19.5], ...
	'Style','edit', ...
	'Tag','Year', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[171 146.25 18 19.5], ...
	'Style','edit', ...
	'Tag','Month', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[189 146.25 18 19.5], ...
	'Style','edit', ...
	'Tag','Day', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl subjmod, ekgmhl subjhl, ekgmhl dathl', ...
	'Enable','off', ...
	'FontSize',10, ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[297 16.5 56.25 18.75], ...
	'String','Change', ...
	'Tag','OKButns', ...
	'UserData',0, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl subjend', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[358.5 16.5 56.25 18.75], ...
	'String','Close', ...
	'Tag','CancelButns', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ekgmhl subjhl, ekgmhl dathl', ...
	'Position',[231.75 144.75 138 117.75], ...
	'String',mat2, ...
	'Style','listbox', ...
	'Tag','SubjList', ...
	'Value',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[233.25 261.75 135.75 18], ...
	'String','Subjects', ...
	'Style','text', ...
	'Tag','SubjListT', ...
	'UserData',2, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl subjclear, ekgmhl subjhl, ekgmhl dathl', ...
	'Enable','off', ...
	'FontSize',10, ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[234.75 16.5 56.25 18.75], ...
	'String','Delete', ...
	'Tag','DelButns', ...
	'UserData',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ekgmhl deloff, ekgmhl dathl', ...
	'CreateFcn','ekgmhl dathl', ...
	'Position',[67.5 78 142.5 45.75], ...
	'Style','listbox', ...
	'Tag','DataList', ...
	'Value',3, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[67.5 123.75 141 14.25], ...
	'String','Data', ...
	'Style','text', ...
	'Tag','DataListT', ...
	'UserData',3, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[234 78.75 135 45], ...
	'Style','edit', ...
	'Tag','Det', ...
	'UserData',2, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[234 123.75 132.75 14.25], ...
	'String','Details', ...
	'Style','text', ...
	'Tag','DetT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl workinit, ekgmhl workslide', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[69.75 53.25 36.75 18.75], ...
	'String','Open', ...
	'Tag','OpeButnd', ...
	'UserData',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl datmod, ekgmhl dathl', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[113.25 53.25 36.75 18.75], ...
	'String','Change', ...
	'Tag','ModButnd', ...
	'UserData',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl datclear, ekgmhl dathl', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[156.75 53.25 36.75 18.75], ...
	'String','Delete', ...
	'Tag','DelButnd', ...
	'UserData',1, ...
	'Visible','off');
h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'Box','on', ...
	'ButtonDownFcn','ekgmhl buttdown, ekgmhl workslide', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat5, ...
	'Position',[29 76 399 324], ...
	'Tag','Axes1', ...
	'Visible','off', ...
	'XAxisLocation','top', ...
	'XColor',[0 0 0], ...
	'XLim',[0.005 3.005], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[-20 20], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[1.497462311557789 22.72445820433436 9.160254037844386], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.2135929648241206 -0.1857585139318871 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.2135929648241206 22.47678018575851 9.160254037844386], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[1.497462311557789 23.46749226006192 9.160254037844386], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(h2,'Parent'),'Title',h2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.831372549019608 0.815686274509804 0.784313725490196], ...
	'Callback','ekgmhl workslide', ...
	'ListboxTop',0, ...
	'Max',2799877, ...
	'Min',1, ...
	'Position',[20.25 39.75 299.25 16.5], ...
	'SliderStep',[0.0001607213459734124 0.0004285902559290998], ...
	'Style','slider', ...
	'Tag','XSlid', ...
	'UserData',0, ...
	'Value',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl workslide', ...
	'ListboxTop',0, ...
	'Max',100, ...
	'Min',-100, ...
	'Position',[319.5 57 17.25 243.75], ...
	'SliderStep',[0.01 0.05], ...
	'Style','slider', ...
	'Tag','YSlid', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl xdec, ekgmhl workslide', ...
	'ListboxTop',0, ...
	'Position',[37.5 7.625 20.25 14.25], ...
	'String','x -', ...
	'Tag','XWinMinus', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl xinc, ekgmhl workslide', ...
	'ListboxTop',0, ...
	'Position',[63.75 7.625 20.25 14.25], ...
	'String','x +', ...
	'Tag','XWinPlus', ...
	'UserData',3, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl yinc, ekgmhl workslide', ...
	'ListboxTop',0, ...
	'Position',[90 7.625 20.25 14.25], ...
	'String','y -', ...
	'Tag','YWinMinus', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl ydec, ekgmhl workslide', ...
	'ListboxTop',0, ...
	'Position',[116.25 7.625 20.25 14.25], ...
	'String','y +', ...
	'Tag','YWinPlus', ...
	'UserData',20, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[36.75 23.25 47.25 12.75], ...
	'String','X size', ...
	'Style','text', ...
	'Tag','XWinT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[89.25 23.25 47.25 12.75], ...
	'String','Y size', ...
	'Style','text', ...
	'Tag','YWinT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl rfind, ekgmhl workslide', ...
	'ListboxTop',0, ...
	'Position',[348 267.75 57 18.75], ...
	'String','R detection', ...
	'Tag','FindButt', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','ekgmhl delbox', ...
	'ListboxTop',0, ...
	'Position',[348 238.5 57 20.25], ...
	'String','Clear', ...
	'Style','checkbox', ...
	'Tag','DelBox', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','ekgmhl insbox', ...
	'ListboxTop',0, ...
	'Position',[347.25 213 57 20.25], ...
	'String','Insert', ...
	'Style','checkbox', ...
	'Tag','InsBox', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl process, ekgmhl results', ...
	'ListboxTop',0, ...
	'Position',[348 163.5 57 18.75], ...
	'String','Process', ...
	'Tag','ProcButt', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl worksave', ...
	'ListboxTop',0, ...
	'Position',[348 129.75 57 18.75], ...
	'String','Save', ...
	'Tag','SaveButt', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[348 188.25 65.25 20.25], ...
	'String','Local max', ...
	'Style','checkbox', ...
	'Tag','MaxBox', ...
	'Value',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[37.5 272.25 152.25 28.5], ...
	'String','Descriptive statistics', ...
	'Style','text', ...
	'Tag','StatT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[224.25 272.25 152.25 27.75], ...
	'String','Fractal results', ...
	'Style','text', ...
	'Tag','FracT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36 244.4375 80.25 19.5], ...
	'String','Mean RR:', ...
	'Style','text', ...
	'Tag','RMeanRRT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36 215.375 80.25 19.5], ...
	'String','min RR:', ...
	'Style','text', ...
	'Tag','RMinRRT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36 186.5 80.25 19.5], ...
	'String','max RR:', ...
	'Style','text', ...
	'Tag','RMaxRRT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36 156.375 80.25 19.5], ...
	'String','mean frequ.:', ...
	'Style','text', ...
	'Tag','RMeanFT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36.75 126.75 80.25 19.5], ...
	'String','SDNN:', ...
	'Style','text', ...
	'Tag','RSDNNT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36.75 98.25 80.25 19.5], ...
	'String','SDANN:', ...
	'Style','text', ...
	'Tag','RSDANNT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36 68.25 80.25 19.5], ...
	'String','RMSSD:', ...
	'Style','text', ...
	'Tag','RRMST', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36 38.375 80.25 19.5], ...
	'String','NN50:', ...
	'Style','text', ...
	'Tag','RNN50T', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36 9 80.25 19.5], ...
	'String','pNN50:', ...
	'Style','text', ...
	'Tag','RpNN50T', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 245.1875 65.25 18], ...
	'Style','edit', ...
	'Tag','RMeanRR', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 216 65.25 18], ...
	'Style','edit', ...
	'Tag','RMinRR', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 187.25 65.25 18], ...
	'Style','edit', ...
	'Tag','RMaxRR', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 157.125 65.25 18], ...
	'Style','edit', ...
	'Tag','RMeanF', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 127.0625 65.25 18], ...
	'Style','edit', ...
	'Tag','RSDNN', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 97.25 65.25 18], ...
	'Style','edit', ...
	'Tag','RSDANN', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 67.75 65.25 18], ...
	'Style','edit', ...
	'Tag','RRMS', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 39.125 65.25 18], ...
	'Style','edit', ...
	'Tag','RNN50', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 9.75 65.25 18], ...
	'Style','edit', ...
	'Tag','RpNN50', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[223.5 244.4375 80.25 19.5], ...
	'String','PSD (beta):', ...
	'Style','text', ...
	'Tag','RPSDT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[223.5 215.375 80.25 19.5], ...
	'String','DFA (alpha1):', ...
	'Style','text', ...
	'Tag','RDFAA1T', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[223.5 186.5 80.25 19.5], ...
	'String','DFA (alpha2):', ...
	'Style','text', ...
	'Tag','RDFAA2T', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[223.5 156.375 80.25 19.5], ...
	'String','DFA (beta`):', ...
	'Style','text', ...
	'Tag','RDFABT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','center', ...
	'ListboxTop',0, ...
	'Position',[223.5 126.3125 152.25 19.5], ...
	'String','Classification NA', ...
	'Style','text', ...
	'Tag','ClassT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Enable','off', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[223.5 96.5 80.25 19.5], ...
	'String','Disp (H):', ...
	'Style','text', ...
	'Tag','RDispT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Enable','off', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[223.5 67 80.25 19.5], ...
	'String','bdSWV (H):', ...
	'Style','text', ...
	'Tag','RSWVT', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[309.75 245.1875 65.25 18], ...
	'Style','edit', ...
	'Tag','RPSD', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[309.75 216.125 65.25 18], ...
	'Style','edit', ...
	'Tag','RDFAA1', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[309.75 187.25 65.25 18], ...
	'Style','edit', ...
	'Tag','RDFAA2', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[309.75 157.125 65.25 18], ...
	'Style','edit', ...
	'Tag','RDFAB', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[309.75 97.25 65.25 18], ...
	'Style','edit', ...
	'Tag','RDisp', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[309.75 67.75 65.25 18], ...
	'Style','edit', ...
	'Tag','RSWV', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl RRHistB', ...
	'ListboxTop',0, ...
	'Position',[225 47.25 70.5 18.75], ...
	'String','RR histogram', ...
	'Tag','RRHistB', ...
	'UserData',0, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl RRTachB', ...
	'ListboxTop',0, ...
	'Position',[305.25 47.25 70.5 18.75], ...
	'String','RR tachogram', ...
	'Tag','RRTachB', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl RRScatB', ...
	'ListboxTop',0, ...
	'Position',[225 28.5 70.5 18.75], ...
	'String','Scatterplot (SP)', ...
   'Visible','off', ...
   'Tag','RRScatB');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl RRPhasB', ...
	'ListboxTop',0, ...
	'Position',[305.25 28.5 70.5 18.75], ...
	'String','Phaseplot (PP)', ...
   'Visible','off', ...
	'Tag','RRPhasB');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','ekgmhl RRScatAB', ...
	'ListboxTop',0, ...
	'Position',[225 9.75 70.5 18.75], ...
	'String','SP animation', ...
   'Visible','off', ...
	'Tag','RRScatAB');
h1 = uicontrol('Parent',h0, ...
	'CreateFcn','ekgmhl destall, ekgmhl subjinit, ekgmhl subjhl', ...
	'Units','points', ...
	'Callback','ekgmhl RRPhasAB', ...
	'ListboxTop',0, ...
	'Position',[305.25 9.75 70.5 18.75], ...
	'String','PP animation', ...
   'Visible','off', ...
	'Tag','RRPhasAB');
if nargout > 0, fig = h0; end
